### ISSUE TITLE
Off Topic (sorry!)

### ISSUE THREAD

**Issue by tabletseeker** [Jac-Zac/My-home-config#2]
Hi, ytfzf support is pretty much dead and we've been trying to get a hold of the contributors.

Would you happen to know which environment variables are needed for ueberzug, kitty, sixel etc to display thumbnails correctly with ytfzf?

Whenever the user is switched with `sudo  su - user` the thumbnail display stops working entirely.

There must be some environment variables which are unset during the user switch but needed by ytfzf and thumb viewers.

`WINDOWID` is definitely one of them, but there must be more. Any idea maybe?

**Comment by Jac-Zac** [comment]
No worries but I’m sorry I didn’t work on that part. I do now really know

**Comment by tabletseeker** [comment]
Ah ok no problem, thank your for replying!

We'll keep trying :-)
